### ISSUE TITLE
xorg-libx11-1.8.10 not available for aarch

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/xorg-libx11-feedstock#44]
### Comment:

I believe the token got reset. Merging xorg-libx11-1.8.10 would "fix" things

**Comment by hmaarrfk** [comment]
First the build failed.

I tried to restart it today, but the upload isn't working.

**Comment by pkgw** [comment]
Yeah, see also #45. By "merging xorg-libx11-1.8.10", do you mean #43?

**Comment by hmaarrfk** [comment]
i mean merging #43 or creating a dummy commit would also fix things.

**Comment by pkgw** [comment]
I've merged #43 and that appears to have addressed the issue.

**Comment by hmaarrfk** [comment]
great i think trimming the package will help
